stages:
  - build
  - deploy

variables:
  GET_SOURCES_ATTEMPTS: 2

build:
  image: node:14-alpine
  stage: build
  cache:
    paths:
      - .yarn-cache/
  artifacts:
    paths:
      - artifact.tar.gz
    expire_in: 2 weeks
    exclude:
      - .yarn-cache/**
  before_script:
    - yarn config set cache-folder "$(pwd)/.yarn-cache"
  script:
    - yarn install
    - yarn build
    - cd dist
    - tar -czf ../artifact.tar.gz .
    - cd ..
    

Production:
  image: alpine
  stage: deploy
  environment:
    name: production
    url: https://studieporten.com
  before_script:
   - apk add openssh-client
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
  script:
   - scp -o StrictHostKeyChecking=no artifact.tar.gz bestservice@webhost.ironlions.fi:~/
   - >
     ssh -o StrictHostKeyChecking=no bestservice@webhost.ironlions.fi "
       tar zxf artifact.tar.gz -C deploy;
       cp public_html/.htaccess ./ht.tmp;
       rm -rf artifact.tar.gz public_html;
       mv deploy public_html;
       mv ./ht.tmp public_html/.htaccess;
     "
  #when: manual
  #only:
  # - master
  dependencies:
    - build
