stages:
  - build
  - deploy

variables:
  GET_SOURCES_ATTEMPTS: 2

build:
  image: node:14-alpine
  stage: build
  cache:
    paths:
      - .yarn-cache/
  artifacts:
    paths:
      - artifact.tar.gz
    expire_in: 2 weeks
    exclude:
      - .yarn-cache/**
  before_script:
    - yarn config set cache-folder "$(pwd)/.yarn-cache"
  script:
    - yarn install
    - yarn build
    - tar -czf /artifact.tar.gz/dist .
    

Production:
  image: alpine
  stage: deploy
  environment:
    name: production
    url: https://studieporten.com
  before_script:
   - apk add openssh-client
   - eval $(ssh-agent -s)
   - echo "$SSH_PRIVATE_KEY" | tr -d '\r' | ssh-add -
   - mkdir -p ~/.ssh
   - chmod 700 ~/.ssh
  script:
   - scp -o StrictHostKeyChecking=no artifact.tar.gz studiepo@webhost.ironlions.fi:~/public_html
   - >
     ssh -o StrictHostKeyChecking=no studiepo@webhost.ironlions.fi "
       cd ~/public_html/;
       rm -rf temp && mkdir temp;
       tar zxf artifact.tar.gz -C temp;
       rm -rf artifact.tar.gz node_modules dist package.json;
       mv temp/* .;
       rm -rf temp;
     "
  #when: manual
  #only:
  # - master
  dependencies:
    - build
